s = "have a Nice day"
print(s)
print(s.upper())
print(s.lower())
print(s.capitalize())
print(s.title())
print(s.swapcase())
print(s.center(50))
print(s.center(50, '#'))
print(s.center(50, '~'))
print(s.replace("Nice", "Good"))
print(s.find('day'))
print(s.find('Nice'))
print(s.index('Nice'))
print(s.count('a'))
print(s.split())

print(type(s))
print(dir(s))
print(len(s))